// <auto-generated />
using System;
using ApiPlantas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPlantas.Migrations
{
    [DbContext(typeof(MinimalContextDb))]
<<<<<<<< HEAD:ApiPlantas/Migrations/20230605225850_initial.Designer.cs
    [Migration("20230605225850_initial")]
    partial class initial
========
    [Migration("20230602215626_inital")]
    partial class inital
>>>>>>>> 1f73794472cf9a422e527072716d47d7125470d9:ApiPlantas/Migrations/20230602215626_inital.Designer.cs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiPlantas.Models.ArduinoData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Humity")
                        .HasColumnType("float");

                    b.Property<bool>("LightOn")
                        .HasColumnType("bit");

                    b.Property<double>("Luminosity")
                        .HasColumnType("float");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<bool>("PumpOn")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("ArduinoDatas", (string)null);
                });

            modelBuilder.Entity("ApiPlantas.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Hours")
                        .HasColumnType("float");

                    b.Property<double>("Humity")
                        .HasColumnType("float");

<<<<<<<< HEAD:ApiPlantas/Migrations/20230605225850_initial.Designer.cs
                    b.Property<string>("ImageBase64")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

========
>>>>>>>> 1f73794472cf9a422e527072716d47d7125470d9:ApiPlantas/Migrations/20230602215626_inital.Designer.cs
                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<double>("Luminosity")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Plants", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
